# Generated by Django 5.0.9 on 2024-09-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_comment_is_positive"),
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="cards",
            field=models.ManyToManyField(related_name="channels", to="cards.card"),
        ),
    ]
