apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hackyeah.proxy.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.hackyeah.proxy.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.hackyeah.proxy.appName }}
  ports:
    - name: http
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hackyeah.proxy.appName }}
  namespace: {{.Values.namespace}}
  labels:
    app: {{ .Values.hackyeah.proxy.appName }}
spec:
  replicas: {{ .Values.hackyeah.proxy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.hackyeah.proxy.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.hackyeah.proxy.appName}}
    spec:
      imagePullSecrets:
        - name: k8sacrauth
      containers:
        - name: {{.Values.hackyeah.proxy.appName}}
          image: "{{ .Values.hackyeah.proxy.image.name}}:{{.Values.hackyeah.proxy.image.tag}}"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              memory: {{ .Values.hackyeah.proxy.resources.requests.memory }}
              cpu: {{ .Values.hackyeah.proxy.resources.requests.cpu }}
            limits:
              memory: {{ .Values.hackyeah.proxy.resources.limits.memory }}
              cpu: {{ .Values.hackyeah.proxy.resources.limits.cpu }}
