# Generated by Django 5.0.9 on 2024-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_comment_is_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="card",
            name="tags",
        ),
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(related_name="cards", to="cards.tag"),
        ),
    ]
