# Generated by Django 5.0.9 on 2024-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_tag_remove_card_tags_card_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="difficulty",
            field=models.TextField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="expected_time",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
