namespace: dev
domain: "devazeno.pl"

hackyeah:
  proxy:
    appName: proxy
    replicas: 1
    image:
      name: hackyeah2024.azurecr.io/proxy
      tag: 1.0.0
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
