apiVersion: v1
kind: Service
metadata:
  name: {{.Values.hackyeah.api.appName}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.hackyeah.api.appName}}
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hackyeah.api.appName }}
data:
  DJ_DEBUG: "{{ .Values.hackyeah.api.debug }}"
  DJ_ALLOWED_HOSTS: "{{ .Values.hackyeah.api.allowedHosts }}"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.hackyeah.api.appName}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{ .Values.hackyeah.api.appName }}
spec:
  replicas: {{ .Values.hackyeah.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.hackyeah.api.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.hackyeah.api.appName }}
    spec:
      imagePullSecrets:
        - name: k8sacrauth
      initContainers:
        - name: collectstatic
          image: "{{ .Values.hackyeah.api.image.name}}:{{.Values.hackyeah.api.image.tag}}"
          envFrom:
            - secretRef:
                name: {{ .Values.hackyeah.api.appName }}
          command:
            - python
            - manage.py
            - collectstatic
            - --noinput
      containers:
        - name: {{ .Values.hackyeah.api.appName }}
          image: "{{ .Values.hackyeah.api.image.name}}:{{.Values.hackyeah.api.image.tag}}"
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: {{ .Values.hackyeah.api.resources.requests.memory }}
              cpu: {{ .Values.hackyeah.api.resources.requests.cpu }}
            limits:
              memory: {{ .Values.hackyeah.api.resources.limits.memory }}
              cpu: {{ .Values.hackyeah.api.resources.limits.cpu }}
          envFrom:
            - secretRef:
                name: {{ .Values.hackyeah.api.appName }}
            - configMapRef:
                name: {{.Values.hackyeah.api.appName}}
{{/*          startupProbe:*/}}
{{/*            httpGet:*/}}
{{/*              port: 8000*/}}
{{/*              path: /api/v1/health/*/}}
{{/*              scheme: HTTP*/}}
{{/*              httpHeaders:*/}}
{{/*                - name: X-Health*/}}
{{/*                  value: "Kubernetes-Health"*/}}
{{/*                - name: Host*/}}
{{/*                  value: localhost*/}}
{{/*            periodSeconds: 5*/}}
{{/*            failureThreshold: 20*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              port: 8000*/}}
{{/*              path: /api/v1/health/*/}}
{{/*              scheme: HTTP*/}}
{{/*              httpHeaders:*/}}
{{/*                - name: X-Health*/}}
{{/*                  value: "Kubernetes-Health"*/}}
{{/*                - name: Host*/}}
{{/*                  value: localhost*/}}
{{/*            periodSeconds: 5*/}}
{{/*            failureThreshold: 1*/}}
