name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
      - 'charts/app/**'

env:
  AZURE_CONTAINER_REGISTRY: hackyeah2024.azurecr.io
  IMAGE_NAME: app
  AKS_RESOURCE_GROUP: hackyeah
  AKS_CLUSTER_NAME: hackyeah
  KUBERNETES_NAMESPACE: dev
  HELM_RELEASE_NAME: app
  CHART_DIRECTORY: ./charts/app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./api

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.0'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS using Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ${{ env.CHART_DIRECTORY }} \
          --namespace ${{ env.KUBERNETES_NAMESPACE }} \
          --set hackyeah.app.image.name=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }} \
          --set hackyeah.app.image.tag=latest