name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
    paths:
      - 'proxy/**'
      - 'charts/proxy/**'


env:
  AZURE_CONTAINER_REGISTRY: hackyeah2024.azurecr.io
  IMAGE_NAME: proxy
  AKS_RESOURCE_GROUP: hackyeah
  AKS_CLUSTER_NAME: hackyeah
  KUBERNETES_NAMESPACE: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./api

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
